name: Sitemap Generator

on:
  push:
    paths:
      - 'menu.json'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Create local changes
      run: |
        npm ci
        npm run generate-sitemap --if-present
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sitemap.xml
        git commit -m "[GitHubBotRunner] Sitemap.xml was updated."
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push "${remote_repo}" HEAD:${GITHUB_REF} --follow-tags;
    - name: Trigger GitHubPage rebuild
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        curl -XPOST -H"Authorization: token ${ACCESS_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds
